### ISSUE TITLE
How do I use "base url" in ejs

### ISSUE THREAD

**Issue by Kuniwak** [jaredhanson/kerouac#8]
How do I use `'base url'` property that is set by `site.use(kerouac.url());` in ejs?

**Comment by WaelChorfan** [comment]
**inside your app.js (main express app file ) :** 
`app.locals.baseURL = "http://someurl"`

**and in any of your ejs views files :**
`<link rel="icon" href="<%=baseURL%>/images/logo.ico">`

You may want to check it  like this  `<p><%=baseURL%></p>`

**Comment by Kuniwak** [comment]
Thank you! 😃

**Comment by Chethan-Gowda** [comment]
Thanks a lot dude, WaelChorfan

**Comment by yurri-yeskov** [comment]
@WaelChorfan, Thanks a lot! :)
